version: '3.1'
services:
  db:
    image: postgres:15-alpine
#    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cms
      LANG: ja_JP.utf8
      TZ: "Asia/Tokyo"
    command: postgres -c 'max_connections=1000'
    volumes:
      - database:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  database:
