-- liquibase formatted sql

-- changeset taku:1691145799593-1
CREATE TABLE "approval_flow" ("approval_flow_id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "fist_approver" BIGINT, "last_modified_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "second_approver" BIGINT, "version" BIGINT NOT NULL, "created_by" VARCHAR(255) NOT NULL, "last_modified_by" VARCHAR(255) NOT NULL, CONSTRAINT "approval_flow_pkey" PRIMARY KEY ("approval_flow_id"));
COMMENT ON TABLE "approval_flow" IS '承認フロー';
COMMENT ON COLUMN "approval_flow"."approval_flow_id" IS '承認フローID';
COMMENT ON COLUMN "approval_flow"."created_date" IS '作成日時';
COMMENT ON COLUMN "approval_flow"."fist_approver" IS '第１承認者';
COMMENT ON COLUMN "approval_flow"."last_modified_date" IS '最終更新日時';
COMMENT ON COLUMN "approval_flow"."second_approver" IS '第２承認者';
COMMENT ON COLUMN "approval_flow"."version" IS 'バージョン(排他制御用)';
COMMENT ON COLUMN "approval_flow"."created_by" IS '作成者';
COMMENT ON COLUMN "approval_flow"."last_modified_by" IS '最終更新者';

-- changeset taku:1691145799593-2
CREATE TABLE "confirm_histroy" ("check_status" SMALLINT NOT NULL, "execute_date" date NOT NULL, "confirm_id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "equip_id" BIGINT, "execute_by" BIGINT, "last_modified_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "version" BIGINT NOT NULL, "created_by" VARCHAR(255) NOT NULL, "last_modified_by" VARCHAR(255) NOT NULL, CONSTRAINT "confirm_histroy_pkey" PRIMARY KEY ("confirm_id"));
COMMENT ON TABLE "confirm_histroy" IS '棚卸し履歴';
COMMENT ON COLUMN "confirm_histroy"."confirm_id" IS '棚卸し履歴ID';
COMMENT ON COLUMN "confirm_histroy"."created_date" IS '作成日時';
COMMENT ON COLUMN "confirm_histroy"."equip_id" IS '備品ID';
COMMENT ON COLUMN "confirm_histroy"."last_modified_date" IS '最終更新日時';
COMMENT ON COLUMN "confirm_histroy"."version" IS 'バージョン(排他制御用)';
COMMENT ON COLUMN "confirm_histroy"."created_by" IS '作成者';
COMMENT ON COLUMN "confirm_histroy"."last_modified_by" IS '最終更新者';

-- changeset taku:1691145799593-3
CREATE TABLE "employee" ("status" SMALLINT NOT NULL, "created_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "emp_id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "last_modified_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "organization_id" BIGINT, "position_id" BIGINT, "version" BIGINT NOT NULL, "created_by" VARCHAR(255) NOT NULL, "email" VARCHAR(255), "emp_name" VARCHAR(255) NOT NULL, "last_modified_by" VARCHAR(255) NOT NULL, "password" VARCHAR(255) NOT NULL, CONSTRAINT "employee_pkey" PRIMARY KEY ("emp_id"));
COMMENT ON TABLE "employee" IS '従業員';
COMMENT ON COLUMN "employee"."status" IS 'ステータス';
COMMENT ON COLUMN "employee"."created_date" IS '作成日時';
COMMENT ON COLUMN "employee"."emp_id" IS '従業員ID';
COMMENT ON COLUMN "employee"."last_modified_date" IS '最終更新日時';
COMMENT ON COLUMN "employee"."organization_id" IS '所属部署';
COMMENT ON COLUMN "employee"."position_id" IS '役職';
COMMENT ON COLUMN "employee"."version" IS 'バージョン(排他制御用)';
COMMENT ON COLUMN "employee"."created_by" IS '作成者';
COMMENT ON COLUMN "employee"."email" IS 'メールアドレス';
COMMENT ON COLUMN "employee"."emp_name" IS '従業員氏名';
COMMENT ON COLUMN "employee"."last_modified_by" IS '最終更新者';
COMMENT ON COLUMN "employee"."password" IS 'パスワード';

-- changeset taku:1691145799593-4
CREATE TABLE "equip_type" ("status" SMALLINT NOT NULL, "created_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "equip_type_id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "last_modified_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "version" BIGINT NOT NULL, "created_by" VARCHAR(255) NOT NULL, "equip_type" VARCHAR(255) NOT NULL, "last_modified_by" VARCHAR(255) NOT NULL, CONSTRAINT "equip_type_pkey" PRIMARY KEY ("equip_type_id"));
COMMENT ON TABLE "equip_type" IS '備品タイプ';
COMMENT ON COLUMN "equip_type"."status" IS 'ステータス';
COMMENT ON COLUMN "equip_type"."created_date" IS '作成日時';
COMMENT ON COLUMN "equip_type"."equip_type_id" IS '備品タイプID';
COMMENT ON COLUMN "equip_type"."last_modified_date" IS '最終更新日時';
COMMENT ON COLUMN "equip_type"."version" IS 'バージョン(排他制御用)';
COMMENT ON COLUMN "equip_type"."created_by" IS '作成者';
COMMENT ON COLUMN "equip_type"."equip_type" IS '備品タイプ名';
COMMENT ON COLUMN "equip_type"."last_modified_by" IS '最終更新者';

-- changeset taku:1691145799593-5
CREATE TABLE "manage_equip" ("purchase_date" date NOT NULL, "created_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "equip_id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "equip_type_id" BIGINT, "last_modified_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "owner_id" BIGINT, "version" BIGINT NOT NULL, "created_by" VARCHAR(255) NOT NULL, "equip_name" VARCHAR(255) NOT NULL, "last_modified_by" VARCHAR(255) NOT NULL, "note" VARCHAR(255), CONSTRAINT "manage_equip_pkey" PRIMARY KEY ("equip_id"));
COMMENT ON TABLE "manage_equip" IS '部品管理台帳';
COMMENT ON COLUMN "manage_equip"."purchase_date" IS '購入日';
COMMENT ON COLUMN "manage_equip"."created_date" IS '作成日時';
COMMENT ON COLUMN "manage_equip"."equip_id" IS '備品ID';
COMMENT ON COLUMN "manage_equip"."last_modified_date" IS '最終更新日時';
COMMENT ON COLUMN "manage_equip"."owner_id" IS '所有者(利用者)';
COMMENT ON COLUMN "manage_equip"."version" IS 'バージョン(排他制御用)';
COMMENT ON COLUMN "manage_equip"."created_by" IS '作成者';
COMMENT ON COLUMN "manage_equip"."equip_name" IS '備品名';
COMMENT ON COLUMN "manage_equip"."last_modified_by" IS '最終更新者';
COMMENT ON COLUMN "manage_equip"."note" IS 'メモ';

-- changeset taku:1691145799593-6
CREATE TABLE "organization" ("status" SMALLINT NOT NULL, "created_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "director_id" BIGINT, "last_modified_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "organization_id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "parent_id" BIGINT, "version" BIGINT NOT NULL, "created_by" VARCHAR(255) NOT NULL, "group_name" VARCHAR(255) NOT NULL, "last_modified_by" VARCHAR(255) NOT NULL, CONSTRAINT "organization_pkey" PRIMARY KEY ("organization_id"));
COMMENT ON TABLE "organization" IS '部署';
COMMENT ON COLUMN "organization"."status" IS 'ステータス';
COMMENT ON COLUMN "organization"."created_date" IS '作成日時';
COMMENT ON COLUMN "organization"."director_id" IS '部門長ID';
COMMENT ON COLUMN "organization"."last_modified_date" IS '最終更新日時';
COMMENT ON COLUMN "organization"."organization_id" IS '部署ID';
COMMENT ON COLUMN "organization"."parent_id" IS '親部署ID';
COMMENT ON COLUMN "organization"."version" IS 'バージョン(排他制御用)';
COMMENT ON COLUMN "organization"."created_by" IS '作成者';
COMMENT ON COLUMN "organization"."group_name" IS '部署名';
COMMENT ON COLUMN "organization"."last_modified_by" IS '最終更新者';

-- changeset taku:1691145799593-7
CREATE TABLE "position" ("status" SMALLINT NOT NULL, "created_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "last_modified_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "position_id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "version" BIGINT NOT NULL, "created_by" VARCHAR(255) NOT NULL, "last_modified_by" VARCHAR(255) NOT NULL, "position_name" VARCHAR(255) NOT NULL, CONSTRAINT "position_pkey" PRIMARY KEY ("position_id"));
COMMENT ON TABLE "position" IS '役職';
COMMENT ON COLUMN "position"."status" IS 'ステータス';
COMMENT ON COLUMN "position"."created_date" IS '作成日時';
COMMENT ON COLUMN "position"."last_modified_date" IS '最終更新日時';
COMMENT ON COLUMN "position"."position_id" IS '役職ID';
COMMENT ON COLUMN "position"."version" IS 'バージョン(排他制御用)';
COMMENT ON COLUMN "position"."created_by" IS '作成者';
COMMENT ON COLUMN "position"."last_modified_by" IS '最終更新者';
COMMENT ON COLUMN "position"."position_name" IS '役職名';

-- changeset taku:1691145799593-8
CREATE TABLE "request_equip" ("progress_state" SMALLINT, "request_date" date, "approval_flow_id" BIGINT, "created_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "equip_type_id" BIGINT, "last_modified_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "request_id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "requester_id" BIGINT, "version" BIGINT NOT NULL, "created_by" VARCHAR(255) NOT NULL, "equip_name" VARCHAR(255), "last_modified_by" VARCHAR(255) NOT NULL, "note" VARCHAR(255), "reason" VARCHAR(255), CONSTRAINT "request_equip_pkey" PRIMARY KEY ("request_id"));
COMMENT ON TABLE "request_equip" IS '購入依頼';
COMMENT ON COLUMN "request_equip"."progress_state" IS 'ProgressStateID';
COMMENT ON COLUMN "request_equip"."request_date" IS '購入依頼日';
COMMENT ON COLUMN "request_equip"."approval_flow_id" IS '承認フローID';
COMMENT ON COLUMN "request_equip"."created_date" IS '作成日時';
COMMENT ON COLUMN "request_equip"."equip_type_id" IS '備品タイプ';
COMMENT ON COLUMN "request_equip"."last_modified_date" IS '最終更新日時';
COMMENT ON COLUMN "request_equip"."request_id" IS '購入依頼ID';
COMMENT ON COLUMN "request_equip"."requester_id" IS '購入依頼者';
COMMENT ON COLUMN "request_equip"."version" IS 'バージョン(排他制御用)';
COMMENT ON COLUMN "request_equip"."created_by" IS '作成者';
COMMENT ON COLUMN "request_equip"."equip_name" IS '購入品名';
COMMENT ON COLUMN "request_equip"."last_modified_by" IS '最終更新者';
COMMENT ON COLUMN "request_equip"."note" IS '備考';
COMMENT ON COLUMN "request_equip"."reason" IS '購入依頼理由';

-- changeset taku:1691145799593-9
CREATE TABLE "account_roles" ("roles" SMALLINT, "account_username" VARCHAR(255) NOT NULL);

-- changeset taku:1691145799593-10
CREATE TABLE "account" ("created_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "last_modified_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "version" BIGINT NOT NULL, "profile" VARCHAR(1000), "allowed_ip" VARCHAR(255), "api_key" VARCHAR(255), "created_by" VARCHAR(255) NOT NULL, "department" VARCHAR(255), "email" VARCHAR(255), "first_name" VARCHAR(255), "image_uuid" VARCHAR(255), "last_modified_by" VARCHAR(255) NOT NULL, "last_name" VARCHAR(255), "password" VARCHAR(255), "status" VARCHAR(255), "url" VARCHAR(255), "username" VARCHAR(255) NOT NULL, CONSTRAINT "account_pkey" PRIMARY KEY ("username"));
COMMENT ON TABLE "account" IS 'ユーザアカウント';
COMMENT ON COLUMN "account"."created_date" IS '作成日時';
COMMENT ON COLUMN "account"."last_modified_date" IS '最終更新日時';
COMMENT ON COLUMN "account"."version" IS 'バージョン(排他制御用)';
COMMENT ON COLUMN "account"."profile" IS 'プロフィール';
COMMENT ON COLUMN "account"."allowed_ip" IS 'ログイン許可IPアドレス';
COMMENT ON COLUMN "account"."api_key" IS 'API KEY';
COMMENT ON COLUMN "account"."created_by" IS '作成者';
COMMENT ON COLUMN "account"."department" IS '所属';
COMMENT ON COLUMN "account"."email" IS 'メールアドレス';
COMMENT ON COLUMN "account"."first_name" IS '名';
COMMENT ON COLUMN "account"."image_uuid" IS '画像UUID';
COMMENT ON COLUMN "account"."last_modified_by" IS '最終更新者';
COMMENT ON COLUMN "account"."last_name" IS '姓';
COMMENT ON COLUMN "account"."password" IS 'パスワード';
COMMENT ON COLUMN "account"."status" IS 'ステータス';
COMMENT ON COLUMN "account"."url" IS 'URL';
COMMENT ON COLUMN "account"."username" IS 'ユーザID';

-- changeset taku:1691145799593-11
ALTER TABLE "request_equip" ADD CONSTRAINT "request_equip_approval_flow_id_key" UNIQUE ("approval_flow_id");

-- changeset taku:1691145799593-12
ALTER TABLE "account" ADD CONSTRAINT "account_api_key_key" UNIQUE ("api_key");

-- changeset taku:1691145799593-13
CREATE TABLE "test_master" ("id" VARCHAR(255) NOT NULL, "test" VARCHAR(255), CONSTRAINT "test_master_pkey" PRIMARY KEY ("id"));
COMMENT ON TABLE "test_master" IS 'テストマスター';
COMMENT ON COLUMN "test_master"."id" IS '主キー';
COMMENT ON COLUMN "test_master"."test" IS 'テスト項目';

-- changeset taku:1691145799593-14
ALTER TABLE "account_roles" ADD CONSTRAINT "fk_account_roles_01" FOREIGN KEY ("account_username") REFERENCES "account" ("username") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset taku:1691145799593-15
ALTER TABLE "approval_flow" ADD CONSTRAINT "fk_approval_flow_01" FOREIGN KEY ("fist_approver") REFERENCES "employee" ("emp_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset taku:1691145799593-16
ALTER TABLE "approval_flow" ADD CONSTRAINT "fk_approval_flow_02" FOREIGN KEY ("second_approver") REFERENCES "employee" ("emp_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset taku:1691145799593-17
ALTER TABLE "confirm_histroy" ADD CONSTRAINT "fk_confirm_history_01" FOREIGN KEY ("equip_id") REFERENCES "manage_equip" ("equip_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset taku:1691145799593-18
ALTER TABLE "confirm_histroy" ADD CONSTRAINT "fk_confirm_history_02" FOREIGN KEY ("execute_by") REFERENCES "employee" ("emp_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset taku:1691145799593-19
ALTER TABLE "employee" ADD CONSTRAINT "fk_employee_01" FOREIGN KEY ("organization_id") REFERENCES "organization" ("organization_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset taku:1691145799593-20
ALTER TABLE "employee" ADD CONSTRAINT "fk_employee_02" FOREIGN KEY ("position_id") REFERENCES "position" ("position_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset taku:1691145799593-21
ALTER TABLE "manage_equip" ADD CONSTRAINT "fk_manage_equip_01" FOREIGN KEY ("equip_type_id") REFERENCES "equip_type" ("equip_type_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset taku:1691145799593-22
ALTER TABLE "manage_equip" ADD CONSTRAINT "fk_manage_equip_02" FOREIGN KEY ("owner_id") REFERENCES "employee" ("emp_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset taku:1691145799593-23
ALTER TABLE "request_equip" ADD CONSTRAINT "fk_request_equip_01" FOREIGN KEY ("equip_type_id") REFERENCES "equip_type" ("equip_type_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset taku:1691145799593-24
ALTER TABLE "request_equip" ADD CONSTRAINT "fk_request_equip_02" FOREIGN KEY ("requester_id") REFERENCES "employee" ("emp_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset taku:1691145799593-25
ALTER TABLE "request_equip" ADD CONSTRAINT "fk_request_equip_03" FOREIGN KEY ("approval_flow_id") REFERENCES "approval_flow" ("approval_flow_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

